//question  1 :==



/*Write a program to take three variables to store your birth date, birth month, and birth year, respectively, and then print them one by one in a specified order.
*/



// const input = require("readline-sync");
// let d = input.questionInt("enter the  value of date :");
// let m = input.questionInt("enter the value of month:");
// let y = input.questionInt("enter the value year :");
// console.log("birthday date",d);
// console.log("birthday month ", m);
// console.log("birthday year ",y);




//question 2 :==


/*Write a program to take input from the user, and then print it to the output.*/ 




// const input = require("readline-sync");
// let n = input.questionInt("enter the number:");
// console.log(n);




// question 3 :==




/*Write a program to take two values from the user and swap them.  */




// const input = require("readline-sync");
// let a = input.questionInt("Enter the 1 number:");
// let b = input.questionInt("Enter the 2 number:");
// let t;
// t = a;
// a = b;
// b = t;
// console.log(a,b);





//question 4 :==



/*Write a program to take two numbers from the user and perform Six basic operations (addition, subtraction, multiplication, division, integer division and modulus) on those two numbers. */




// const input = require("readline-sync");
// let a = input.questionInt("enter the 1 number;");
// let b = input.questionInt("enter the 2 number:");
// a = a+b;
// s = a-b;
// ma = a*b;
// d = a/b;
// m = a%b;
// i = Math.floor(a/b);
// console.log(a,s,m,d,ma,i); 





//QUESTION 5 :==



/*Write a program to take two numbers A and B from the user and calculate the quotient and remainder when number A is divided by number B. */




// const input = require("readline-sync");
// let a = input.questionInt("enter the first number:");
// let b = input.questionInt("enter the second number:");
//  q =Math.floor (a/b);
//  r = a%b;
//  console.log(q,r);





//question 6 :==




/*Write a program to take a positive number from the user and then display the last digit of that number. */





// const input = require("readline-sync");
// let n = input.questionInt("enter the value:");
//   a = n%10;
//   console.log(a); 






// question 7 :==




/*Write a program to convert a temperature from Celsius to Fahrenheit using the formula C/5 = (F-32)/9 */




// const input = require("readline-sync");
// let c = input.questionInt("enter the value:");
// let b = (c*9/5)+32
// console.log( b );





// question 8 :==





/*Write a program to take two inputs from the user and swap them without using a temporary or third variable. */




// const input = require("readline-sync");
// let a = input.questionInt("enter the first number:");
// let b = input.questionInt("enter the second  vlaue: ");
// [a,b]=[b,a]
// console.log("a:",a);
// console.log("b:",b);






//question 9 :==



/*Write a program to take two numbers, A and B from the user. Your task is to find the largest number that is less than A and can be divided evenly by B. Can you figure out that number? */




// const input = require("readline-sync");

// let a = input.questionInt("enter the 1 value:");
// let b = input.questionInt("enter the 2 value");
//  c = Math.floor(a/b);
//  n = c*b
//  console.log(n);

